name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check required secrets (main only)
        if: github.ref == 'refs/heads/main'
        run: |
          test -n "${{ secrets.SENDGRID_API_KEY }}" || (echo "Missing secret: SENDGRID_API_KEY" && exit 1)
          test -n "${{ secrets.SEND_FROM }}" || (echo "Missing secret: SEND_FROM" && exit 1)
          test -n "${{ secrets.CONTACT_RECIPIENT }}" || (echo "Missing secret: CONTACT_RECIPIENT" && exit 1)

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Run unit tests
        run: npm run test:unit

      - name: Test Redis connectivity (optional)
        env:
          REDIS_URL: ${{ secrets.REDIS_URL }}
        run: |
          node --version
          node scripts/check-redis.js || (echo "Redis connectivity failed" && exit 1)

      - name: Run lint
        run: npm run lint

      - name: Build
        run: npm run build

      - name: Start preview server
        run: |
          npm run preview &
          npx wait-on http://localhost:5173

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npx playwright test --config=playwright.config.js

      - name: Upload test results (if any)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report || ''
